# Generated by Django 3.0.7 on 2020-11-30 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('mailing_list', '0002_auto_20201121_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglistevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Profile'),
        ),
    ]
