# Generated by Django 3.2.5 on 2021-12-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0007_donation_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingprogression',
            name='context_of_click',
            field=models.CharField(max_length=200, null=True, verbose_name='Contexte du clic'),
        ),
    ]
