# Generated by Django 3.0.7 on 2020-11-30 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('clickcollect', '0006_auto_20201102_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickandcollect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Profile'),
        ),
    ]
